const express = require('express');
const router = express.Router();
const db = require('../database/database');

// 1. GET /api/students — Retrieve all students from SQLite
router.get('/students', (req, res) => {
  const sql = 'SELECT * FROM students';

  db.all(sql, [], (err, rows) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    res.status(200).json(rows);
  });
});

// 2. GET /api/students/:id — Retrieve a single student by ID
router.get('/students/:id', (req, res) => {
  const sql = 'SELECT * FROM students WHERE id = ?';
  const studentId = req.params.id;

  db.get(sql, [studentId], (err, row) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    if (!row) {
      return res.status(404).json({ error: 'Student not found' });
    }
    res.status(200).json(row);
  });
});

// 3. POST /api/students — Insert a new student into SQLite
router.post('/students', (req, res) => {
  const { name, email, department } = req.body;

  if (!name || !email || !department) {
    return res.status(400).json({ error: 'name, email, and department are required' });
  }

  const sql = 'INSERT INTO students (name, email, department) VALUES (?, ?, ?)';
  const params = [name, email, department];

  db.run(sql, params, function (err) {
    if (err) {
      return res.status(500).json({ error: err.message });
    }

    // `this.lastID` contains the auto-incremented primary key generated by SQLite
    const createdStudent = {
      id: this.lastID,
      name,
      email,
      department
    };

    res.status(201).json(createdStudent);
  });
});

// 4. PATCH /api/students/:id — Update an existing student partially
router.patch('/students/:id', (req, res) => {
  const studentId = req.params.id;

  // First check if the student exists
  db.get('SELECT * FROM students WHERE id = ?', [studentId], (err, student) => {
    if (err) {
      return res.status(500).json({ error: err.message });
    }
    if (!student) {
      return res.status(404).json({ error: 'Student not found' });
    }

    const { name, email, department } = req.body;

    // Use new values if provided, otherwise keep existing values
    const updatedName = name !== undefined ? name : student.name;
    const updatedEmail = email !== undefined ? email : student.email;
    const updatedDepartment = department !== undefined ? department : student.department;

    const sql = 'UPDATE students SET name = ?, email = ?, department = ? WHERE id = ?';
    const params = [updatedName, updatedEmail, updatedDepartment, studentId];

    db.run(sql, params, function (updateErr) {
      if (updateErr) {
        return res.status(500).json({ error: updateErr.message });
      }

      res.status(200).json({
        id: Number(studentId),
        name: updatedName,
        email: updatedEmail,
        department: updatedDepartment
      });
    });
  });
});

// 5. DELETE /api/students/:id — Delete a student from SQLite
router.delete('/students/:id', (req, res) => {
  const studentId = req.params.id;

  const sql = 'DELETE FROM students WHERE id = ?';

  db.run(sql, [studentId], function (err) {
    if (err) {
      return res.status(500).json({ error: err.message });
    }

    // `this.changes` is the number of rows affected by the query
    if (this.changes === 0) {
      return res.status(404).json({ error: 'Student not found' });
    }

    res.status(200).json({
      message: 'Student deleted successfully'
    });
  });
});

module.exports = router;
